name: "Code Checks"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  checkov-scan:
    name: Checkov Scan
    permissions:
      contents: read
      security-events: write # Allow the workflow to upload analysis results
      actions: read # Allow the workflow to read actions metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@fa9edf8f0a491c59a924ea6accd5bdcf07752cff # v12.3107.0
        with:
          directory: .
          framework: terraform
          output_format: cli
          output_file_path: console

  codeql-checks:
    name: CodeQL Analysis
    permissions:
      contents: read
      security-events: write # Allow the workflow to upload analysis results
    strategy:
      matrix:
        language: [actions]
    uses: JackPlowman/reusable-workflows/.github/workflows/codeql-analysis.yml@770e0f8d83d2cf12795ae93c33ff48b731c41201 # v2026.06.30.01
    with:
      language: ${{ matrix.language }}

  common-code-checks:
    name: Common Code Checks
    permissions:
      contents: read
      actions: read # Allow the workflow to read actions metadata
      pull-requests: write # Allow the workflow to create and modify pull request comments
      security-events: write # Allow the workflow to upload analysis results
    uses: JackPlowman/reusable-workflows/.github/workflows/common-code-checks.yml@770e0f8d83d2cf12795ae93c33ff48b731c41201 # v2026.06.30.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}

  tflint-scan:
    name: TFLint Scan
    permissions:
      contents: read
      actions: read # Allow the workflow to read actions metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        with:
          tflint_version: v0.60.0
      - name: TFLint Init
        run: just tflint-init
      - name: TFLint Check
        run: just tflint-check

  tofu-validate:
    name: Tofu Validate
    permissions:
      contents: read
      security-events: write # Allow the workflow to upload analysis results
      actions: read # Allow the workflow to read actions metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_version: 1.11.2
      - name: Tofu Init
        run: just tofu-init
      - name: Tofu Validate
        run: just tofu-validate
