name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions: {}

jobs:
  common-pull-request-tasks:
    name: Common Pull Request Tasks
    permissions:
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-pull-request-tasks.yml@6b4711103e199f3074829c2a6ce600eb9f904cc4 # v2025.05.16.06
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
